spring.application.name=ope-incentivos-api

spring.datasource.url=${URL:jdbc:postgresql://localhost:5432/incentivos}
spring.datasource.username=${DB_USER:myuser}
spring.datasource.password=${DB_PASSWORD:mypassword}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# SpringDoc OpenAPI (Swagger) Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html